### ISSUE TITLE
pydal to connect to app in standalone mode but can't open database

### ISSUE THREAD

**Issue by achatte** [web2py/pydal#140]
from pydal import DAL, Field
db = DAL('sqlite://storage.sqlite',folder='C:...\web2py_new\web2py_new\applications\my_application_name\databases',auto_import=True);
db.commit()

-------------------------------------------------------------------------------
Gives the following error:
------------------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\Ron\AppData\Local\Enthought\Canopy\User\lib\site-packages\pydal-15.02.27-py2.7.egg\pydal\base.py", line 434, in __init__
    self._adapter = ADAPTERS[self._dbname](**kwargs)
  File "C:\Users\Ron\AppData\Local\Enthought\Canopy\User\lib\site-packages\pydal-15.02.27-py2.7.egg\pydal\adapters\base.py", line 54, in __call__
    obj = super(AdapterMeta, cls).__call__(*args, **kwargs)
  File "C:\Users\Ron\AppData\Local\Enthought\Canopy\User\lib\site-packages\pydal-15.02.27-py2.7.egg\pydal\adapters\sqlite.py", line 78, in __init__
    if do_connect: self.reconnect()
  File "C:\Users\Ron\AppData\Local\Enthought\Canopy\User\lib\site-packages\pydal-15.02.27-py2.7.egg\pydal\connection.py", line 99, in reconnect
    self.connection = f()
  File "C:\Users\Ron\AppData\Local\Enthought\Canopy\User\lib\site-packages\pydal-15.02.27-py2.7.egg\pydal\adapters\sqlite.py", line 76, in connector
    return self.driver.Connection(dbpath, **driver_args)
OperationalError: unable to open database file

**Comment by achatte** [comment]
I found the issue: 
Its about having the folder location in windows way as oppose to linux/unix. If I use fwd slash, instead backwards. It works.
