### ISSUE TITLE
Running tests on the local machine

### ISSUE THREAD

**Issue by kirsn** [web2py/pydal#19]
Initially reported on the forum: https://groups.google.com/forum/#!topic/web2py-developers/tVZ-jYKgEF0
I recently cloned the pydal repository, and imported it into Eclipse (Luna).
Went ahead and right-clicked on the "tests" folder, and selected the "Run As > Python unit-test" option.
The output I see in the Eclipse console, is below.

```
Finding files... done.
Importing test modules ... Testing against sqlite engine (sqlite:memory)
Testing against sqlite engine (sqlite:memory)
done.


======================================================================
ERROR: testRun (tests.nosql.TestImportExportUuidFields)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\code\git\pydal\tests\nosql.py", line 774, in testRun
    db.import_from_csv_file(stream)
  File "D:\code\git\pydal\pydal\base.py", line 1125, in import_from_csv_file
    *args, **kwargs)
  File "D:\code\git\pydal\pydal\objects.py", line 969, in import_from_csv_file
    curr_id = self.insert(**dict(items))
  File "D:\code\git\pydal\pydal\objects.py", line 736, in insert
    ret =  self._db._adapter.insert(self, self._listify(fields))
  File "D:\code\git\pydal\pydal\adapters\base.py", line 714, in insert
    raise e
IntegrityError: foreign key constraint failed

======================================================================
ERROR: testInsert (tests.nosql.TestRNameFields)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\code\git\pydal\tests\nosql.py", line 1186, in testInsert
    self.assertEqual(isinstance(db.tt.insert(aa='1'), long), True)
  File "D:\code\git\pydal\pydal\objects.py", line 736, in insert
    ret =  self._db._adapter.insert(self, self._listify(fields))
  File "D:\code\git\pydal\pydal\adapters\base.py", line 714, in insert
    raise e
OperationalError: near "very": syntax error

======================================================================
ERROR: testRun (tests.nosql.TestRNameFields)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\code\git\pydal\tests\nosql.py", line 1117, in testRun
    self.assertEqual(isinstance(db.tt.insert(aa='x'), long), True)
  File "D:\code\git\pydal\pydal\objects.py", line 736, in insert
    ret =  self._db._adapter.insert(self, self._listify(fields))
  File "D:\code\git\pydal\pydal\adapters\base.py", line 714, in insert
    raise e
OperationalError: near "very": syntax error

======================================================================
ERROR: testSelect (tests.nosql.TestRNameFields)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\code\git\pydal\tests\nosql.py", line 1003, in testSelect
    Field('rating', 'integer', rname=rname2, default=2)
  File "D:\code\git\pydal\pydal\base.py", line 821, in define_table
    table = self.lazy_define_table(tablename,*fields,**args)
  File "D:\code\git\pydal\pydal\base.py", line 858, in lazy_define_table
    polymodel=polymodel)
  File "D:\code\git\pydal\pydal\adapters\base.py", line 458, in create_table
    self.create_sequence_and_triggers(query,table)
  File "D:\code\git\pydal\pydal\adapters\base.py", line 1299, in create_sequence_and_triggers
    self.execute(query)
  File "D:\code\git\pydal\pydal\adapters\base.py", line 1318, in execute
    return self.log_execute(*a, **b)
  File "D:\code\git\pydal\pydal\adapters\base.py", line 1312, in log_execute
    ret = self.cursor.execute(command, *a[1:], **b)
OperationalError: near "from": syntax error



======================================================================
ERROR: testSelect (tests.nosql.TestRNameTable)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\code\git\pydal\tests\nosql.py", line 907, in testSelect
    rname=rname
  File "D:\code\git\pydal\pydal\base.py", line 821, in define_table
    table = self.lazy_define_table(tablename,*fields,**args)
  File "D:\code\git\pydal\pydal\base.py", line 858, in lazy_define_table
    polymodel=polymodel)
  File "D:\code\git\pydal\pydal\adapters\base.py", line 458, in create_table
    self.create_sequence_and_triggers(query,table)
  File "D:\code\git\pydal\pydal\adapters\base.py", line 1299, in create_sequence_and_triggers
    self.execute(query)
  File "D:\code\git\pydal\pydal\adapters\base.py", line 1318, in execute
    return self.log_execute(*a, **b)
  File "D:\code\git\pydal\pydal\adapters\base.py", line 1312, in log_execute
    ret = self.cursor.execute(command, *a[1:], **b)
OperationalError: near "very": syntax error



----------------------------------------------------------------------
Ran 88 tests in 1.907s

FAILED (errors=5, skipped=3)
---------------------------------------------------------------------------------------
```

**Comment by kirsn** [comment]
Took the current pydal repo, and repeated the steps posted above. 
```
D:\code\git\pydal [master]> git log
commit 39d7df7538199473458a0d92adbbcc0747e3bf01
Merge: 338b792 7e065cc
Author: Giovanni Barillari <gi0baro@d4net.org>
Date:   Fri Apr 3 00:51:12 2015 +0200

    Merge pull request #122 from niphlod/fix/README2

    fix badges from #121
```
The results are identical - tests do not pass within Eclipse - except for the last summary lines
```

----------------------------------------------------------------------
Ran 104 tests in 2.156s

FAILED (errors=5, skipped=4)
```

When run from the command prompt, it seems to works though. The number of tests are **60**
```
D:\code\git\pydal [master]> python -m unittest tests
Testing against sqlite engine (sqlite:memory)
........s...................................................
----------------------------------------------------------------------
Ran 60 tests in 0.797s

OK (skipped=1)
```

Not sure what to make of this:
* Should this work from within Eclipse at all?
* Why the discrepancy in the number of tests being run - Eclipse is 104, Cmd is 60?

**Comment by niphlod** [comment]
eclipse is definitely doing something wrong.

**Comment by kirsn** [comment]
If I select the `/pydal/tests/__init__.py` and "Run As > Python unit-test", from within Eclipse, then the output matches that of the command line, and all tests run and pass.

You are right; it is probably an issue with the way Pydev runs these tests. Will close this issue.
