### ISSUE TITLE
<type 'exceptions.TypeError'> __init__() got an unexpected keyword argument 'snapshot'

### ISSUE THREAD

**Issue by franciscocosta** [web2py/pydal#268]
On the new `web2py 2.12.2-stable+timestamp.2015.08.09.14.29.44` I'm getting this error on the MongoDB adapter:

        Traceback (most recent call last):
      File "/home/franciscocosta/www/web2py/gluon/restricted.py", line 227, in restricted
        exec ccode in environment
      File "/home/franciscocosta/www/web2py/applications/emprego/models/db.py", line 1482, in <module>
        db.applications.status.default = db(db.applications_status.name == T('Por Analisar', lazy=False)).select().first().id if db(db.applications_status.name == T('Por Analisar', lazy=False)).select().first() else None
      File "/home/franciscocosta/www/web2py/gluon/packages/dal/pydal/objects.py", line 2026, in select
        return adapter.select(self.query,fields,attributes)
      File "/home/franciscocosta/www/web2py/gluon/packages/dal/pydal/adapters/mongo.py", line 324, in select
        limit=limitby_limit, sort=mongosort_list, snapshot=snapshot)
      File "/usr/local/lib/python2.7/dist-packages/pymongo/collection.py", line 929, in find
        return Cursor(self, *args, **kwargs)
    TypeError: __init__() got an unexpected keyword argument 'snapshot'

If I remove the `snapshot argument` on line 324 it works ok.

**Comment by stephenrauch** [comment]
@mdipierro @niphlod @franciscocosta 

This is an older version of the MongoDB driver.

In 2.12.2, \gluon\packages\dal\CHANGES says:

```
Version 15.03
-------------

Released on March 23rd 2015
```

**Comment by franciscocosta** [comment]
I've used the source from web2py.com

**Comment by stephenrauch** [comment]
@mdipierro @niphlod

There appears to have been some sort of reversion in the web2py package.  Web2py ``Version 2.11.2-stable+timestamp.2015.05.30.16.33.24`` included the following in \gluon\packages\dal\CHANGES: 

```
pydal changelog
===============

Version 15.05.29
----------------

Released on May 29th 2015
```

while web2py ``Version 2.12.2-stable+timestamp.2015.08.09.14.29.44``  \gluon\packages\dal\CHANGES says:

```
pydal changelog
===============

Version 15.03
-------------

Released on March 23rd 2015
```

**Comment by gi0baro** [comment]
I'm closing this since something went wrong with web2py release, is not pydal related.

**Comment by sbourgeois1** [comment]
This problem seems to persist in 2.12.3
127.0.0.1.2015-11-19.10-25-35.5f680a84-b65f-47ab-a9c7-734c0f698d65

<type 'exceptions.TypeError'> grid() got an unexpected keyword argument 'submit_button'

Version
web2py™	Version 2.12.3-stable+timestamp.2015.08.19.00.18.03
Python	Python 2.7.6: /home/sbourgeois/web2py/virtenv/bin/python (prefix: /home/sbourgeois/web2py/virtenv)
Traceback
1.
2.
3.
4.
5.
6.
7.
8.
9.
10.
11.
12.
Traceback (most recent call last):
  File "/home/sbourgeois/web2py/libs/gluon/restricted.py", line 227, in restricted
    exec ccode in environment
  File "/home/sbourgeois/web2py/wsgi/web2py/applications/mst/controllers/stk_trans.py", line 2736, in <module>
  File "/home/sbourgeois/web2py/libs/gluon/globals.py", line 412, in <lambda>
    self._caller = lambda f: f()
  File "/home/sbourgeois/web2py/wsgi/web2py/applications/mst/controllers/stk_trans.py", line 953, in stock_transaction_03
    searchable = False,
  File "/home/sbourgeois/web2py/libs/gluon/sqlhtml.py", line 3045, in smartgrid
    user_signature=user_signature, **kwargs)
TypeError: grid() got an unexpected keyword argument 'submit_button'
