### ISSUE TITLE
<type 'exceptions.TypeError'> object_id argument must be of type ObjectId or an objectid representable integer

### ISSUE THREAD

**Issue by franciscocosta** [web2py/pydal#286]
In some table I have `auth.signature`

When saving a form on `form.process().accepted`  i get the error `<type 'exceptions.TypeError'> object_id argument must be of type ObjectId or an objectid representable integer`

On https://github.com/web2py/pydal/blob/master/pydal/adapters/mongo.py on line 226 I've changed to this:

            elif fieldtype.startswith("reference") or fieldtype == "id":
                #value = self.object_id(obj)
                value = self.object_id(NoSQLAdapter.represent(self, obj, fieldtype))

and it seams to work well

**Comment by gi0baro** [comment]
@stephenrauch do you see any concern about this?

**Comment by stephenrauch** [comment]
@gi0baro

My primary concern would be that:

```
value = self.object_id(obj)
```

should always return an ObjectID. So while the suggested change may solve the particular case at hand, with some sort of side effect, the problem will likely pop up again later.

@franciscocosta

Can you supply the complete stack trace or a test case for when this happens?

**Comment by franciscocosta** [comment]
@stephenrauch sure!

    <type 'exceptions.TypeError'> object_id argument must be of type ObjectId or an objectid representable integer

# Version

    web2py™	Version 2.12.3-stable+timestamp.2015.08.19.00.18.03
    Python	Python 2.7.6: /usr/local/bin/uwsgi (prefix: /usr)

# Traceback

    Traceback (most recent call last):
      File "/home/franciscocosta/www/web2py/gluon/restricted.py", line 227, in restricted
        exec ccode in environment
      File "/home/franciscocosta/www/web2py/applications/emprego/controllers/backoffice.py", line 1373, in <module>
      File "/home/franciscocosta/www/web2py/gluon/globals.py", line 412, in <lambda>
        self._caller = lambda f: f()
      File "/home/franciscocosta/www/web2py/applications/emprego/controllers/backoffice.py", line 1040, in empresa
        if form.process().accepted:
      File "/home/franciscocosta/www/web2py/gluon/html.py", line 2301, in process
        self.validate(**kwargs)
      File "/home/franciscocosta/www/web2py/gluon/html.py", line 2238, in validate
        if self.accepts(**kwargs):
      File "/home/franciscocosta/www/web2py/gluon/sqlhtml.py", line 1709, in accepts
        self.id_field_name]).update(**fields)
      File "/home/franciscocosta/www/web2py/gluon/packages/dal/pydal/objects.py", line 2036, in update
        ret = db._adapter.update("%s" % table._tablename,self.query,fields)
      File "/home/franciscocosta/www/web2py/gluon/packages/dal/pydal/adapters/mongo.py", line 808, in update
        expanded = MongoDBAdapter.Expanded(self, 'update', query, fields)
      File "/home/franciscocosta/www/web2py/gluon/packages/dal/pydal/adapters/mongo.py", line 301, in __init__
        self._expand_fields(self._fields_loop_abort)
      File "/home/franciscocosta/www/web2py/gluon/packages/dal/pydal/adapters/mongo.py", line 407, in _expand_fields
        self._expand_field(field, value, mid_loop)
      File "/home/franciscocosta/www/web2py/gluon/packages/dal/pydal/adapters/mongo.py", line 418, in _expand_field
        expanded = self.adapter.expand(value, field.type)
      File "/home/franciscocosta/www/web2py/gluon/packages/dal/pydal/adapters/mongo.py", line 616, in expand
        result = self.represent(expression, field_type)
      File "/home/franciscocosta/www/web2py/gluon/packages/dal/pydal/adapters/mongo.py", line 220, in represent
        value = self.object_id(obj)
      File "/home/franciscocosta/www/web2py/gluon/packages/dal/pydal/adapters/mongo.py", line 168, in object_id
        "ObjectId or an objectid representable integer")
    TypeError: object_id argument must be of type ObjectId or an objectid representable integer
    Error snapshot  help
    <type 'exceptions.TypeError'>(object_id argument must be of type ObjectId or an objectid representable integer)

**Comment by stephenrauch** [comment]
@franciscocosta 

I am still unable to duplicate this. It would be helpful to see the table definition for the table failing in the update.  Also, can you reproduce the error after changing in `object_id()`:

```python                      
                      
if not isinstance(arg, (int, long)):
    try:
        if isinstance(arg, Row):
            return self.object_id(long(arg))
    except:
        pass
    raise TypeError("object_id argument must be of type " +
                    "ObjectId or an objectid representable integer")
```

to:

```python   
                  
elif isinstance(arg, (Row, Reference)):
    return self.object_id(long(arg['id']))

elif not isinstance(arg, (int, long)):
    raise TypeError("object_id argument must be of type " +
                    "ObjectId or an objectid representable integer" +
                    " (type %s)" % type(arg) )

```

This may fix the problem as it better aligns this behavior with base.represent(), or the exception will give type information for the failed conversion.

**Comment by jurkovicb** [comment]
I have completely repeatable case. In my case the problem is in signature argument.

web2py version: 2.12.3-stable+timestamp.2015.08.19.00.18.03
I have create simple app and set signature to True.

```python
auth.define_tables(username=True, signature=True)
uid = db.auth_user.insert(
    first_name='Admin',
    last_name='Admin',
    username='admin',
    email='admin',
    password='xxxxxxxxx' )
```
After running application I get ticket:
```python
Traceback (most recent call last):
  File "/var/www/web2py/gluon/restricted.py", line 227, in restricted
    exec ccode in environment
  File "/var/www/web2py/applications/mtest/models/db.py", line 69, in <module>
    password='xxxxxxxxxxxx' )
  File "/var/www/web2py/gluon/packages/dal/pydal/objects.py", line 712, in insert
    ret = self._db._adapter.insert(self, self._listify(fields))
  File "/var/www/web2py/gluon/packages/dal/pydal/adapters/mongo.py", line 788, in insert
    values[fieldname] = self.represent(v, fieldtype)
  File "/var/www/web2py/gluon/packages/dal/pydal/adapters/mongo.py", line 227, in represent
    value = self.object_id(obj)
  File "/var/www/web2py/gluon/packages/dal/pydal/adapters/mongo.py", line 177, in object_id
    "ObjectId or an objectid representable integer")
TypeError: object_id argument must be of type ObjectId or an objectid representable integer
```
Hope this helps.

**Comment by gi0baro** [comment]
@stephenrauch maybe related to #223 ?

**Comment by stephenrauch** [comment]
@jurkovicb

Thanks, that test case was perfect...

@gi0baro

I do not believe this bug is directly related to #223, other than the fact that web2py has the inherent equivalence of 'int' and 'id' which MongoDB chafes at.  I think this bug is really a down stream side effect of  https://github.com/web2py/pydal/pull/242#discussion_r33758245 and some missing test coverage.

**Comment by gi0baro** [comment]
@stephenrauch ok, thank you
