### ISSUE TITLE
Oracle DB, Auto-Ticketing on any db insert.

### ISSUE THREAD

**Issue by preactive** [web2py/pydal#322]
---
2.13.2-stable+timestamp.2015.12.18.11.00.46
(Running on Unknown, Python 2.7.5)
---
Red Hat Enterprise Linux Server release 7.1 (Maipo)
kernel 3.10.0-229.7.2.el7.x86_64
----
('Oracle Database 11g Enterprise Edition Release 11.2.0.4.0 - 64bit Production',)
('PL/SQL Release 11.2.0.4.0 - Production',)
('CORE\t11.2.0.4.0\tProduction',)
('TNS for Linux: Version 11.2.0.4.0 - Production',)
('NLSRTL Version 11.2.0.4.0 - Production',)
---

Autoticket:

Traceback (most recent call last):
  File "/opt/www-data/web2py/gluon/restricted.py", line 227, in restricted
    exec ccode in environment
  File "/opt/www-data/web2py/applications/test/controllers/appadmin.py", line 703, in <module>
  File "/opt/www-data/web2py/gluon/globals.py", line 412, in <lambda>
    self._caller = lambda f: f()
  File "/opt/www-data/web2py/applications/test/controllers/appadmin.py", line 151, in insert
    if form.accepts(request.vars, session):
  File "/opt/www-data/web2py/gluon/sqlhtml.py", line 1725, in accepts
    self.vars.id = self.table.insert(**fields)
  File "/opt/www-data/web2py/gluon/packages/dal/pydal/objects.py", line 728, in insert
    ret = self._db._adapter.insert(self, self._listify(fields))
  File "/opt/www-data/web2py/gluon/packages/dal/pydal/adapters/oracle.py", line 233, in insert
    rid = Reference(id)
NameError: global name 'Reference' is not defined
---

Suggested Resolve:
Line 9 of https://github.com/web2py/pydal/blob/master/pydal/adapters/oracle.py
Insert "..helpers.classes import Reference"
------------------------
Sourced from:
https://github.com/web2py/pydal/blob/master/pydal/adapters/mongo.py
Line 9:
"from ..helpers.classes import SQLCustomType, SQLALL, Reference"
---

Notes:
I dont know if 'SQLCustomType' or 'SQLALL' are important to cx_Oracle so I only imported 'Reference' and it seemed to resolve my issue of auto-ticketing. DB records are now being committed.  :)
---
see: https://groups.google.com/forum/#!searchin/web2py/oracle/web2py/4Y1Yx86wzl4 for any other relevant details.

**Comment by preactive** [comment]
Proposed code change: 

https://github.com/web2py/pydal/commit/e526ccf175d381e21c2e58966ed90a9b534a738e

**Comment by gi0baro** [comment]
@preactive please make a Pull Request with your branch
