### ISSUE TITLE
Representer.adapt can not handle unicode input (Python 2.*)

### ISSUE THREAD

**Issue by nursix** [web2py/pydal#354]
Crashing with unicode strings, e.g.
```
>>> field.like(u"%ãy%")
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/dominic/work/web2py/gluon/packages/dal/pydal/objects.py", line 1715, in __repr__
    return '<Query %s>' % BaseAdapter.expand(self.db._adapter, self)
  File "/home/dominic/work/web2py/gluon/packages/dal/pydal/adapters/base.py", line 152, in expand
    return str(expression)
  File "/home/dominic/work/web2py/gluon/packages/dal/pydal/objects.py", line 1718, in __str__
    return str(self.db._adapter.expand(self))
  File "/home/dominic/work/web2py/gluon/packages/dal/pydal/adapters/base.py", line 442, in expand
    rv = op(first, second, **optional_args)
  File "/home/dominic/work/web2py/gluon/packages/dal/pydal/dialects/base.py", line 239, in like
    second = self.expand(second, 'string')
  File "/home/dominic/work/web2py/gluon/packages/dal/pydal/dialects/__init__.py", line 58, in expand
    return self.adapter.expand(*args, **kwargs)
  File "/home/dominic/work/web2py/gluon/packages/dal/pydal/adapters/base.py", line 452, in expand
    rv = self.represent(expression, field_type)
  File "/home/dominic/work/web2py/gluon/packages/dal/pydal/adapters/base.py", line 385, in represent
    return super(SQLAdapter, self).represent(obj, field_type)
  File "/home/dominic/work/web2py/gluon/packages/dal/pydal/adapters/base.py", line 333, in represent
    return self.representer.represent(obj, field_type)
  File "/home/dominic/work/web2py/gluon/packages/dal/pydal/representers/__init__.py", line 248, in represent
    rv = self.get_representer_for_type(field_type)(rv, field_type)
  File "/home/dominic/work/web2py/gluon/packages/dal/pydal/representers/__init__.py", line 207, in _default
    return self.adapt(value)
  File "/home/dominic/work/web2py/gluon/packages/dal/pydal/representers/__init__.py", line 225, in adapt
    value = bytes(value)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe3' in position 1: ordinal not in range(128)
>>> 
```

**Comment by nursix** [comment]
This modification works for me:

    def adapt(self, value):
        if PY2:
            if type(value) is unicode:
                value = bytes(value.encode('utf-8'))
            elif not isinstance(value, bytes):
                value = bytes(value)
            try:
                value.decode(self.adapter.db_codec)
            except:
                value = value.decode('latin1').encode(self.adapter.db_codec)
        else:
            value = to_unicode(value)
        return self.adapter.adapt(value)

**Comment by gi0baro** [comment]
@nursix thanks for the catch. Will inspect this soon.
