### ISSUE TITLE
Decimal type completely broken on SQLite?

### ISSUE THREAD

**Issue by dartg** [web2py/pydal#466]
Maybe I am missing something, but it seems that querying a database that contains a "decimal(n, m)" field always raises an exception.

```
>>> from pydal import DAL, Field
>>> db = DAL("sqlite://:memory:")
>>> db.define_table(
...     "product",
...     Field("title", length=100),
...     Field("price", type="decimal(10, 2)")
... )
<Table product (id, title, price)>
>>> db.product.insert(title="Product 1", price=10.25)
1
>>> db.product.insert(title="Product 2", price=5.10)
2
>>> db.commit()
>>> rows = db(db.product.id > 0).select()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python35\lib\site-packages\pydal\objects.py", line 2210, in select
    return adapter.select(self.query, fields, attributes)
  File "C:\Python35\lib\site-packages\pydal\adapters\sqlite.py", line 82, in select
    return super(SQLite, self).select(query, fields, attributes)
  File "C:\Python35\lib\site-packages\pydal\adapters\base.py", line 760, in select
    return self._select_aux(sql, fields, attributes, colnames)
  File "C:\Python35\lib\site-packages\pydal\adapters\base.py", line 739, in _select_aux
    return processor(rows, fields, colnames, cacheable=cacheable)
  File "C:\Python35\lib\site-packages\pydal\adapters\base.py", line 305, in parse
    for row in rows
  File "C:\Python35\lib\site-packages\pydal\adapters\base.py", line 305, in <listcomp>
    for row in rows
  File "C:\Python35\lib\site-packages\pydal\adapters\base.py", line 231, in _parse
    value = self.parse_value(value, fit, ft, blob_decode)
  File "C:\Python35\lib\site-packages\pydal\adapters\base.py", line 198, in parse_value
    return self.parser.parse(value, field_itype, field_type)
  File "C:\Python35\lib\site-packages\pydal\parsers\__init__.py", line 101, in parse
    return self.registered[field_itype](value, field_type)
  File "C:\Python35\lib\site-packages\pydal\parsers\__init__.py", line 76, in __call__
    return self.call(value, field_type)
  File "C:\Python35\lib\site-packages\pydal\parsers\__init__.py", line 70, in _call_with_extras
    return self.f(self.parser, value, **extras)
  File "C:\Python35\lib\site-packages\pydal\parsers\sqlite.py", line 19, in _decimal
    value = ('%.' + decimals + 'f') % value
ValueError: unsupported format character ' ' (0x20) at index 2
>>>
```

I am using Python 3.5 (also occurs in 2.7) with PyDAL 17.03 on Windows 8 (x64). I haven't tested other database engines.

**Comment by mdipierro** [comment]
Mind that you should use sqlite:memory and not sqlite://:memory: else the DB will be in a file called ":memory:"
