### ISSUE TITLE
_before_insert not work when required=True in latest version

### ISSUE THREAD

**Issue by sugizo** [web2py/pydal#480]
1. create new web2py app named test
2. models/db_test.py
def before_insert_test(f):
    f['field1'] = 'field1'

db.define_table('table0', 
    Field('field0', notnull = True, required = True), 
    Field('field1', notnull = True, required = True) )

db.table0._before_insert.append(before_insert_test)

3. controllers/install.py
def index():
    db.table0.insert(field0 = 'field0')

4. error result
Traceback (most recent call last):
  File "/Users/MacBookPro/site/web2py/gluon/restricted.py", line 219, in restricted
    exec(ccode, environment)
  File "/Users/MacBookPro/site/web2py/applications/test/controllers/install.py", line 6, in <module>
  File "/Users/MacBookPro/site/web2py/gluon/globals.py", line 406, in <lambda>
    self._caller = lambda f: f()
  File "/Users/MacBookPro/site/web2py/applications/test/controllers/install.py", line 4, in index
    db.table0.insert(field0 = 'field0')
  File "/Users/MacBookPro/site/web2py/gluon/packages/dal/pydal/objects.py", line 731, in insert
    row = self._fields_and_values_for_insert(fields)
  File "/Users/MacBookPro/site/web2py/gluon/packages/dal/pydal/objects.py", line 709, in _fields_and_values_for_insert
    'Table: missing required field: %s' % name)
RuntimeError: Table: missing required field: field1

**Comment by gi0baro** [comment]
@mdipierro i think the required check should be moved after the before callbacks to make this work.

**Comment by mdipierro** [comment]
ok with me. What I fix it or will you?

**Comment by gi0baro** [comment]
@mdipierro will inspect the flow during the weekend. I'll keep you updated.

**Comment by abastardi** [comment]
Note, the problem applies to `_before_update` as well. Also, https://github.com/web2py/pydal/commit/d75d5cf5f3d7a106c4b4fc142b28116475208cd2 claims to fix this issue but does not appear to do so.

**Comment by gi0baro** [comment]
@abastardi 
> Now we have:
> 1. Calculate computed values, fill in default values, and check for missing required fields.
> 2. Run the _before_[insert/update] callbacks.

That's not true, the actual flow is:
1. Enqueue for computation or fill default
2. Check required fields empty from point 1
3. Compute computations enqueued from point 1
4. Run callbacks

I think moving callbacks before point 2 is wrong for two reasons:
- you won't have default values filled in callbacks, and if your callbacks relies on computed or fields that are required, it won't work
- you will have to double check empty values

Also, the example given is pointless since it can be achieved putting a default on the involved fields.
Plus, if you want to make things to fields before computation, why you don't just put the modification code on computation?

My final point: the best option I can thing to have a correct flow for everyone here is to add another callback method, for example `before_validation` and put it between point 1 and 2.

**Comment by abastardi** [comment]
>> Now we have:
>> 
>> 1. Calculate computed values, fill in default values, and check for missing required fields.
>> 2. Run the before[insert/update] callbacks.
> 
> That's not true, the actual flow is:
> 
> 1. Enqueue for computation or fill default
> 2. Check required fields empty from point 1
> 3. Compute computations enqueued from point 1
> 4. Run callbacks

I just meant to indicate that everything in 1 happens before 2. The specific ordering of items within 1 was not relevant to my point -- the issue is when the callbacks run relative to 2 and 3 in your list.

> I think moving callbacks before point 2 is wrong for two reasons:

Sorry, I thought you agreed with moving callbacks before 2 (though not necessarily before 3) based on your comment [here](https://github.com/web2py/pydal/issues/480#issuecomment-313641975).

> if your callbacks relies on computed or fields that are required, it won't work

We should think about required fields (at least those that aren't also computed fields) and computed fields separately. First, regarding required fields, while it is true that the callbacks will fail if they depend on a required field that is missing, that is not an argument for checking required fields first, as the failure will happen in either case. On the other hand, if we allow the callbacks to run first, at least they will have an opportunity to fill in missing required fields, thereby preventing an error.

Regarding computed fields, I suppose we could go either way on that. On the one hand, the callbacks might rely on values from the computed fields. On the other hand, the callbacks might alter some of the values used by the computed fields. I would lean toward supporting the latter case, simply as a matter of backward compatibility (i.e., that's the way it was before this change).

> you will have to double check empty values

Sure, but if that's what it takes to get the proper workflow, we should do it. In fact, that's how it was done previously.

> Also, the example given is pointless since it can be achieved putting a default on the involved fields.

Sure, but the bigger issue is one of backward compatibility. This change [broke](https://groups.google.com/d/msg/web2py/w4A9Wo2f6As/ZF1Ax0ZnBAAJ) at least one person's working code. It's not clear what benefit we get from checking required fields after the callbacks, so I would rather not break existing code for the sake of that change.

> Plus, if you want to make things to fields before computation, why you don't just put the modification code on computation?

Are you suggesting that within the code for a computed field we should promote the mutation of *other fields*? The `compute` attribute is associated with a specific field and expected to return a value for that field -- using it to generate external side effects would be unexpected and could cause confusion.

> My final point: the best option I can thing to have a correct flow for everyone here is to add another callback method, for example before_validation and put it between point 1 and 2.

I agree we could add another hook, though I'm not sure it would be worth the complexity. What was wrong with the old approach, though? Were there particular use cases that motivated the switch to the new workflow?

**Comment by gi0baro** [comment]
@abastardi see https://github.com/web2py/pydal/pull/431 for the rationale behind the change.
Again, I can't agree on changing the actual behavior.

> We should think about required fields (at least those that aren't also computed fields) and computed fields separately.

Would make sense if the issue wasn't related to the use of the first in combination with the other ones.
And, for the records, just because something worked in the past doesn't mean it worked *correctly*. I can't see how the upper workflow is right, considering that:
1. if you need to set a default value, you shouldn't use a callback for that
2. if you want to override or set a value in callbacks then there's no valid reason to set that field as required, 'cause **required** means the input should be given on the insert instruction to me, not injected in the flow

And talking about *meanings*, I think we also have a *philosophical* issue here. Because to me a `before_insert` method should be the last thing execute before an insert, without everything happening after. In other words, I consider a *before* callback a sort of barrier before the operation. Considering all of this, I think adding another callback is not a *complexity* issue, rather an additional 'signal' to bind to, and I still consider a better solution for the issue. Changing the order of operation again, will fix certain workflows, but will brake other ones.

**Comment by abastardi** [comment]
>> We should think about required fields (at least those that aren't also computed fields) and computed fields separately.
> 
> Would make sense if the issue wasn't related to the use of the first in combination with the other ones.

I'm not sure what you mean. The reported issue involves `required` fields but no computed fields. We should be able to calculate computed fields before the `_before_` callbacks but still check for `required` fields after. What is wrong with that approach? I guess it's a little less efficient, as you have to loop through the fields one more time (though you could mitigate that by recording the required fields during the first loop and looping over only those fields in the second loop).

> And, for the records, just because something worked in the past doesn't mean it worked correctly.

Right. But just because we now might prefer to support one set of use cases over another set of use cases does not mean we should therefore label the old behavior a bug and use that as an excuse to break backward compatibility.

> I can't see how the upper workflow is right, considering that:
> 
> if you need to set a default value, you shouldn't use a callback for that

First, consider a slightly different callback, where the default value is only set conditionally:

    def before_insert_test(f):
        if some_condition:
            f['field1'] = 'field1'

The above could not be achieved via the `default` argument, which will always assign a value (even if it is `None`).

Second, the point is that in the past, we allowed setting a default via a callback. Just because we now don't like that option doesn't make it a bug that merits breaking backward compatibility. Furthermore, that doesn't make the workflow "wrong," it just means there is some other way to achieve the desired outcome in some cases.

> if you want to override or set a value in callbacks then there's no valid reason to set that field as required, 'cause required means the input should be given on the insert instruction to me, not injected in the flow

I don't see why `required` must take on that particular meaning. It could just as well mean a value is required before making the final submission to the database.

> And talking about meanings, I think we also have a philosophical issue here. Because to me a before_insert method should be the last thing execute before an insert, without everything happening after. In other words, I consider a before callback a sort of barrier before the operation.

First, I don't think it's a philosophical difference -- it's just that we already have some automatic behavior happening before insert, and there are therefore multiple places where callbacks could run in that process. There is no philosophical argument that says the callbacks must come before or after calculating default values or computed values -- we simply have to decide which use cases are most important to support (or we can support both by adding an additional hook, as you suggested).

Second, whatever your preference regarding the ordering of callbacks vs. defaults/computed values, it's not clear why checking required fields must come before the callbacks (again, other than to avoid the extra loop).

> Considering all of this, I think adding another callback is not a complexity issue, rather an additional 'signal' to bind to, and I still consider a better solution for the issue.

Sure, adding complexity is justified if there are real use cases worth supporting. If that's the case here, we should add another callback.

> Changing the order of operation again, will fix certain workflows, but will brake other ones.

I don't object to the new workflow, but I think we should acknowledge that the old behavior was not a bug that would justify breaking backward compatibility. Rather, we just decided we prefer the new workflow and opted to break backward compatibility to support it.

Now, if we're OK changing the web2py policy regarding backward compatibility, we should (a) be explicit about the new policy, and (b) employ a proper process to warn users and document the breakages (and recommended code changes/workarounds). We should not simply make such changes silently and allow code to break and data to be corrupted without warning.

Finally, note that in some apps, this change might not only lead to exceptions being thrown (as reported above), but also to silent corruption of data. For example, consider a `_before_insert` callback that first mutated some submitted values *before* those values were passed on to a computed field. With this change, those computed fields will now be taking in incorrect values, possibly silently corrupting the data (rather than throwing an obvious exception).
