### ISSUE TITLE
PY3 upload into blob error

### ISSUE THREAD

**Issue by maxcrystal** [web2py/pydal#516]
To reproduce the error add in `db.py`:
```py
auth.settings.extra_fields['auth_user'] = [
    Field(
        'photo', 'upload',
        uploadfield='photo_file',
        requires=IS_EMPTY_OR(IS_IMAGE()),
    ),
    Field(
        'photo_file', 'blob',
    ),
]
```
If I try upload an image this error occurs:
```py
<class 'UnicodeDecodeError'> 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte

Traceback (most recent call last):
  File "/Users/max/dev/projects/tukker/web2py/gluon/restricted.py", line 219, in restricted
    exec(ccode, environment)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/max/dev/projects/tukker/web2py/gluon/restricted.py", line 141, in __init__
    self.traceback = traceback.format_exc()
AttributeError: 'NoneType' object has no attribute 'strip'
```

If I change `pydal/parsers/base.py` as suggested here #417 then I am able to upload an image into database but can't download it due to socket error:
```py
ERROR:Rocket.Errors.Thread-6:Traceback (most recent call last):

  File "/Users/max/dev/projects/tukker/web2py/gluon/rocket.py", line 1319, in run
    self.run_app(conn)

  File "/Users/max/dev/projects/tukker/web2py/gluon/rocket.py", line 1841, in run_app
    self.conn.sendall(b('0\r\n\r\n'))

  File "/Users/max/dev/projects/tukker/web2py/gluon/rocket.py", line 155, in _sendall_darwin
    sent = self.socket.send(buf[offset:])

BrokenPipeError: [Errno 32] Broken pipe

ERROR:Rocket.Errors.Thread-6:Tried to send "500 Server Error" to client but received socket error
```

**Comment by ilvalle** [comment]
See https://github.com/web2py/web2py/issues/1861

**Comment by maxcrystal** [comment]
@ilvalle unfortunately this doesn't solve the problem completely. I have tried it before and got this error:
```py
ERROR:Rocket.Errors.Thread-6:Traceback (most recent call last):

  File "/Users/max/dev/projects/tukker/web2py/gluon/rocket.py", line 1319, in run
    self.run_app(conn)

  File "/Users/max/dev/projects/tukker/web2py/gluon/rocket.py", line 1841, in run_app
    self.conn.sendall(b('0\r\n\r\n'))

  File "/Users/max/dev/projects/tukker/web2py/gluon/rocket.py", line 155, in _sendall_darwin
    sent = self.socket.send(buf[offset:])

BrokenPipeError: [Errno 32] Broken pipe

ERROR:Rocket.Errors.Thread-6:Tried to send "500 Server Error" to client but received socket error
```

**Comment by ilvalle** [comment]
@maxcrystal pydal returns a bytes stream https://github.com/web2py/pydal/blob/master/pydal/objects.py#L1779
If the content of the stream is the same of the original file, then the error is either in web2py or in rocket. Could you check it?

**Comment by ilvalle** [comment]
@maxcrystal https://github.com/web2py/web2py/pull/1870 contains the fix for rocket

**Comment by maxcrystal** [comment]
@ilvalle thank you!
