### ISSUE TITLE
executesql() causes IndexError if only colnames is used

### ISSUE THREAD

**Issue by Faelysse** [web2py/pydal#524]
When calling executesql('<some query\>', colnames=["something.something"]), the code causes an IndexError because it tries to access an empty list. 

> Traceback (most recent call last):
  File "/srv/www/web2py/gluon/shell.py", line 274, in run
    execfile(startfile, _env)
  File "/srv/www/web2py/applications/iadev/scripts/test_auction_get_ia116h.py", line 402, in <module>
    test_values_private()
  File "/srv/www/web2py/applications/iadev/scripts/test_auction_get_ia116h.py", line 135, in test_values_private
    rand_user['id'], filters={"private": True})
  File "applications/iadev/modules/auction.py", line 1094, in get_running_sql
    query, user_bids_only = self._build_running_query_sql(user_id, filters)
  File "applications/iadev/modules/auction.py", line 925, in _build_running_query_sql
    colnames=["auction_id"])
  File "/srv/www/web2py/gluon/packages/dal/pydal/base.py", line 821, in executesql
    data, fields=extracted_fields, colnames=colnames)
  File "/srv/www/web2py/gluon/packages/dal/pydal/adapters/base.py", line 305, in parse
    for row in rows
  File "/srv/www/web2py/gluon/packages/dal/pydal/adapters/base.py", line 224, in _parse
    tmp = tmps[j]
IndexError: list index out of range

The tmps[] variable is created in function `_parse_expand_colnames()` in `web2py/gluon/packages/dal/pydal/adapters/base.py,` but as it iterates over fields, none is created (`len(tmps) == 0`)
```python
def _parse_expand_colnames(self, fieldlist):
    ...
    for field in fieldlist:
        ...
        tmps.append(...)
    ....
    return (..., tmps)
```

The value is then accessed by iterating over colnames in `_parse()`, but since `len(tmps) == 0 and len(colnames) >= 1`, the code will cause an `IndexError`, as it will try to access non-existing value.
```python
def _parse(self, row, tmps, fields, colnames, blob_decode,
           cacheable, fields_virtual, fields_lazy):
    ...
    for (j, colname) in enumerate(colnames):
        ...
        tmp = tmps[j]  # causes IndexError here
        ....
```

Having only fields value set and not colnames works, as colnames variable is generated from fields values if not set (None), in `web2py/gluon/packages/dal/pydal/base.py` function `executesql()`

```python
def executesql(self, query, placeholders=None, as_dict=False,
               fields=None, colnames=None, as_ordered_dict=False):
    ...
    if fields or colnames:
        ...
        if not colnames:
                colnames = [f.sqlsafe for f in extracted_fields]
        ....
```

This issue was caused by commit https://github.com/web2py/pydal/commit/5cd99f57816edec300a1974e9db396d1345deb2c and is present in current version (both release and latest repository version)

**Comment by valq7711** [comment]
Hi, @Faelysse!
It is fixed now!
[PR](https://github.com/web2py/pydal/pull/626)

**Comment by Faelysse** [comment]
I am no longer in the company where I worked with web2py, can anyone confirm?

**Comment by valq7711** [comment]
https://github.com/web2py/pydal/blob/4f8dc24a545a60f40b1e2b8b9d20cb4cf07fe94c/tests/sql.py#L2247
