### ISSUE TITLE
Python 3 InDBMigrator error

### ISSUE THREAD

**Issue by cccaballero** [web2py/pydal#545]
Hi, I am using PyDAL in Python 3.5 and when I use the option:

    adapter_args=dict(migrator=InDBMigrator)

In dal constructor is triggering the exception:

> UnicodeDecodeError:  'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte

This is the complete trace

```
Traceback (most recent call last):
  File "/home/carlos.caballero/Software/pycharm-2018.2.4/helpers/pydev/pydevd.py", line 1664, in <module>
    main()
  File "/home/carlos.caballero/Software/pycharm-2018.2.4/helpers/pydev/pydevd.py", line 1658, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/carlos.caballero/Software/pycharm-2018.2.4/helpers/pydev/pydevd.py", line 1068, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/carlos.caballero/Software/pycharm-2018.2.4/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/carlos.caballero/PycharmProjects/asistenteGULCFG/main.py", line 14, in <module>
    run()
  File "/home/carlos.caballero/PycharmProjects/asistenteGULCFG/main.py", line 11, in run
    should_notify()
  File "/home/carlos.caballero/PycharmProjects/asistenteGULCFG/remainder.py", line 43, in should_notify
    db = Database().db
  File "/home/carlos.caballero/PycharmProjects/asistenteGULCFG/utils/singelton.py", line 10, in __call__
    self.instance = self.my_class(*args, **kwargs)
  File "/home/carlos.caballero/PycharmProjects/asistenteGULCFG/database.py", line 20, in __init__
    self.define_tables()
  File "/home/carlos.caballero/PycharmProjects/asistenteGULCFG/database.py", line 25, in define_tables
    Field('event_date', 'date'))
  File "/home/carlos.caballero/PycharmProjects/asistenteGULCFG/pydal/base.py", line 590, in define_table
    table = self.lazy_define_table(tablename, *fields, **kwargs)
  File "/home/carlos.caballero/PycharmProjects/asistenteGULCFG/pydal/base.py", line 624, in lazy_define_table
    polymodel=polymodel)
  File "/home/carlos.caballero/PycharmProjects/asistenteGULCFG/pydal/adapters/base.py", line 798, in create_table
    return self.migrator.create_table(*args, **kwargs)
  File "/home/carlos.caballero/PycharmProjects/asistenteGULCFG/pydal/migrator.py", line 294, in create_table
    tfile = self.file_open(table._dbt, 'rb')
  File "/home/carlos.caballero/PycharmProjects/asistenteGULCFG/pydal/migrator.py", line 518, in file_open
    return DatabaseStoredFile(self.db, filename, mode)
  File "/home/carlos.caballero/PycharmProjects/asistenteGULCFG/pydal/helpers/classes.py", line 522, in __init__
    self.data = datafile.read()
  File "/usr/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte
```

**Comment by ybenitezf** [comment]
the same here
