### ISSUE TITLE
Simple query question

### ISSUE THREAD

**Issue by lucas3F59** [web2py/pydal#573]
Ciao Massimo!

It seems to simple to be wrong, but what's the problem here!? Note that I can view the database using "DB Browser for SQLite".

Thank you very much!

L.

```
#! /usr/bin/env python
# -*- coding: utf-8 -*-

from pydal import DAL, Field

my_dbconn = DAL( 'sqlite://local.sqlite')

table = my_dbconn.my_table( my_dbconn.my_table.my_field != None).select()

for row in table():
    print( row)
```

Result:

```
#   Traceback (most recent call last):
#     File "query.py", line 7, in <module>
#       table = my_dbconn.my_table( my_dbconn.my_table.my_field != None).select()
#     File "C:\python37_AMD64\lib\site-packages\pydal\base.py", line 669, in __getattr__
#       return BasicStorage.__getattribute__(self, key)
#   AttributeError: 'DAL' object has no attribute 'my_table'
```

**Comment by mdipierro** [comment]
my_dbconn.my_table is not a database table. It is a Python object defined by
my_dbconn.define_table('my_table', ....)

That object will create a db table if does not exist and acts as a
proxy for the db table.
In your code there is no my_dbconn.define_table('my_table', ....)
