### ISSUE TITLE
complex orderby doesn't work on datastore

### ISSUE THREAD

**Issue by ilvalle** [web2py/pydal#95]
```
db(db.tt.id > 0).select(orderby=db.tt.aa | db.tt.id)
```
raises
```
Traceback (most recent call last):
  File "tests/nosql.py", line 300, in testRun
    self.assertEqual(db(db.tt.id > 0).select(orderby=db.tt.aa | db.tt.id)[0].aa, '3')
  File "pydal/objects.py", line 2093, in select
    return adapter.select(self.query,fields,attributes)
  File "pydal/adapters/google_adapters.py", line 462, in select
    (items, tablename, fields) = self.select_raw(query,fields,attributes)
  File "pydal/adapters/google_adapters.py", line 420, in select_raw
    _order = orders.get(order, make_order(order))
  File "pydal/adapters/google_adapters.py", line 418, in make_order
    return  (desc and  -getattr(tableobj, s)) or getattr(tableobj, s)
AttributeError: type object 'tt' has no attribute 'id'
```
```
db(db.tt.id > 0).select(orderby=~db.tt.aa | db.tt.id)
```
raises
```
Traceback (most recent call last):
  File "tests/nosql.py", line 300, in testRun
    self.assertEqual(db(db.tt.id > 0).select(orderby=~db.tt.aa | db.tt.id)[0].aa, '3')
  File "pydal/objects.py", line 2093, in select
    return adapter.select(self.query,fields,attributes)
  File "pydal/adapters/google_adapters.py", line 462, in select
    (items, tablename, fields) = self.select_raw(query,fields,attributes)
  File "pydal/adapters/google_adapters.py", line 410, in select_raw
    orderby = self.expand(orderby)
  File "pydal/adapters/google_adapters.py", line 237, in expand
    return expression.op(expression.first, expression.second)
  File "pydal/adapters/google_adapters.py", line 304, in COMMA
    return '%s, %s' % (first.name,second.name)
AttributeError: 'Expression' object has no attribute 'name'
```

**Comment by mdipierro** [comment]
This must be resolved before 2.10.1. Let me know if you are on the case, else I will work on it later today.

**Comment by ilvalle** [comment]
you can fix it; I've just found it by running few tests

**Comment by mdipierro** [comment]
Can you check it my commit fixes it?

**Comment by ilvalle** [comment]
it raises
```
Traceback (most recent call last):
  File "tests/nosql.py", line 302, in testRun
    self.assertEqual(db(db.tt.id > 0).select(orderby=~db.tt.aa | db.tt.id)[0].aa, '3')
  File "pydal/objects.py", line 2093, in select
    return adapter.select(self.query,fields,attributes)
  File "pydal/adapters/google_adapters.py", line 462, in select
    (items, tablename, fields) = self.select_raw(query,fields,attributes)
  File "pydal/adapters/google_adapters.py", line 420, in select_raw
    _order = orders.get(order, make_order(order))
  File "pydal/adapters/google_adapters.py", line 418, in make_order
    else getattr(tableobj, order))
AttributeError: type object 'tt' has no attribute 'tt.id'
```
In this PR  https://github.com/web2py/pydal/pull/96 uncomment https://github.com/web2py/pydal/pull/96/files#diff-aa74af9a1e7abbc9e78191ccef366b72R302 to test this  issue

**Comment by mdipierro** [comment]
one more try?

**Comment by ilvalle** [comment]
Ok, it passed the test

**Comment by mdipierro** [comment]
Thanks for the help.
