### ISSUE TITLE
google datastore error with nonetype in query 

### ISSUE THREAD

**Issue by ilvalle** [web2py/pydal#99]
Query: ``` db(db.tt.id).count()```

raises
```
Traceback (most recent call last):
  File "tests/nosql.py", line 355, in testRun
    db(db.tt.id).count()
  File "pydal/objects.py", line 2083, in count
    return db._adapter.count(self.query,distinct)
  File "pydal/adapters/google_adapters.py", line 481, in count
    (items, tablename, fields) = self.select_raw(query,count_only=True)
  File "pydal/adapters/google_adapters.py", line 353, in select_raw
    filters = self.expand(query)
  File "pydal/adapters/google_adapters.py", line 239, in expand
    return expression.op(expression.first)
  File "pydal/adapters/google_adapters.py", line 286, in NE
    return self.gaef(first,'!=',second)
  File "pydal/adapters/google_adapters.py", line 274, in gaef
    value = self.represent(second,first.type,first._tablename)
  File "pydal/adapters/google_adapters.py", line 157, in represent
    return ndb.Key(tablename, long(obj))
TypeError: long() argument must be a string or a number, not 'NoneType'
```

**Comment by mdipierro** [comment]
this should be fixed
